apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: api-transport
  namespace: tendril
spec:
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 180s
    idleConnTimeout: 300s
