apiVersion: v1
kind: Service
metadata:
  name: tendril-vision-detector
  namespace: tendril
spec:
  selector:
    app: tendril-vision-detector
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
