apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-www
  namespace: tendril
spec:
  redirectRegex:
    regex: "^https?://www\\.tendrilgrow\\.com/(.*)"
    replacement: "https://tendrilgrow.com/${1}"
    permanent: true
