"""Grow type profile definitions — seed data for the 12 built-in grow types."""
from __future__ import annotations

GROW_TYPE_PROFILES: list[dict] = [
    {
        "id": "dwc",
        "name": "DWC (Deep Water Culture)",
        "category": "hydroponic_active",
        "description": "Plants sit in net pots above aerated nutrient solution. Roots submerged 24/7.",
        "terminology": {"container": "Bucket", "space": "Tent", "contents": "Reservoir", "holder": "Net pot", "medium": "Hydroton / Clay pebbles"},
        "sensor_kit": "Hydro Kit",
        "relevant_sensors": ["ph", "ec", "water_temp", "dissolved_oxygen", "water_level", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "water_temp", "water_level"],
        "irrelevant_sensors": ["soil_moisture", "soil_temp", "mist_pressure"],
        "unique_fields": ["air_stone_status", "reservoir_size", "reservoir_change_interval", "top_feed_active"],
        "ph_range": {"min": 5.5, "max": 6.2},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.2, "flower_min": 1.2, "flower_max": 1.8},
        "health_check_questions": ["When did you last change the reservoir?", "Are your air stones running?", "Any slime on the roots?", "Water color/clarity?"],
        "automations": ["ph_auto_dose", "ec_auto_dose", "water_level_topoff", "reservoir_change_reminder", "water_temp_alert", "dissolved_oxygen_alert"],
        "feeding_approach": "Continuous — nutrients always in reservoir. Weekly reservoir change with fresh mix.",
        "nutrient_strength": "50-75%",
        "common_problems": ["Root rot", "pH swings", "Water temp too high", "Algae", "Pump failure"],
        "ai_prompt_context": "DWC grow — roots are submerged in aerated nutrient solution 24/7. Monitor root health, water clarity, dissolved oxygen, and reservoir freshness.",
    },
    {
        "id": "rdwc",
        "name": "RDWC (Recirculating DWC)",
        "category": "hydroponic_active",
        "description": "Connected DWC buckets sharing a central reservoir via circulation pump.",
        "terminology": {"container": "Site", "space": "Tent", "contents": "Reservoir", "holder": "Net pot", "medium": "Hydroton / Clay pebbles", "shared": "Control bucket"},
        "sensor_kit": "Hydro Kit + Flow",
        "relevant_sensors": ["ph", "ec", "water_temp", "dissolved_oxygen", "water_level", "flow_rate", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "water_temp", "flow_rate"],
        "irrelevant_sensors": ["soil_moisture", "soil_temp", "mist_pressure"],
        "unique_fields": ["central_reservoir_size", "connected_sites", "circulation_pump_status", "return_flow_rate", "reservoir_change_interval"],
        "ph_range": {"min": 5.5, "max": 6.2},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.2, "flower_min": 1.2, "flower_max": 1.8},
        "health_check_questions": ["Is the circulation pump running?", "Are all sites getting equal flow?", "Any blockage in return lines?", "When did you last clean the system?"],
        "automations": ["ph_auto_dose", "ec_auto_dose", "water_level_topoff", "reservoir_change_reminder", "circulation_pump_monitor", "flow_rate_alert", "cross_site_variance_alert"],
        "feeding_approach": "Continuous — dosed at central reservoir. Weekly-biweekly change.",
        "nutrient_strength": "50-75%",
        "common_problems": ["Uneven distribution", "Line clogs", "Pump failure", "Root rot", "pH swings"],
        "ai_prompt_context": "RDWC grow — multiple connected DWC sites sharing a central reservoir via circulation pump. Check for uniform distribution, flow issues, and all standard DWC concerns.",
    },
    {
        "id": "nft",
        "name": "NFT (Nutrient Film Technique)",
        "category": "hydroponic_active",
        "description": "Thin film of nutrient solution flows continuously over bare roots in a sloped channel.",
        "terminology": {"container": "Channel", "space": "Tent", "contents": "Nutrient film", "holder": "Net pot", "medium": "Rockwool starter cube"},
        "sensor_kit": "Hydro Kit + Flow",
        "relevant_sensors": ["ph", "ec", "water_temp", "flow_rate", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "flow_rate"],
        "irrelevant_sensors": ["water_level", "dissolved_oxygen", "soil_moisture", "soil_temp", "mist_pressure"],
        "unique_fields": ["channel_count", "channel_length", "flow_rate_target", "reservoir_size", "pump_status", "reservoir_change_interval"],
        "ph_range": {"min": 5.5, "max": 6.5},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.4, "flower_min": 1.2, "flower_max": 2.0},
        "health_check_questions": ["Is the pump running continuously?", "Any channels running dry?", "Root mat blocking flow in any channel?", "Reservoir level adequate?"],
        "automations": ["ph_auto_dose", "ec_auto_dose", "flow_rate_monitor", "pump_failure_alert", "reservoir_level_alert"],
        "feeding_approach": "Continuous flow from reservoir. Weekly reservoir change.",
        "nutrient_strength": "50-75%",
        "common_problems": ["Pump failure (lethal fast)", "Root blockage", "Uneven flow", "Salt buildup"],
        "ai_prompt_context": "NFT grow — thin nutrient film flows over bare roots in channels. Pump failure is critical (roots dry in minutes). Monitor flow rate, root mat health, and channel drainage.",
    },
    {
        "id": "ebb_flow",
        "name": "Ebb & Flow (Flood and Drain)",
        "category": "hydroponic_active",
        "description": "Grow tray periodically floods with nutrient solution then drains back to reservoir.",
        "terminology": {"container": "Tray", "space": "Tent", "contents": "Flood tray", "holder": "Pot", "medium": "Hydroton / Rockwool / Perlite"},
        "sensor_kit": "Hydro Kit",
        "relevant_sensors": ["ph", "ec", "water_temp", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "water_temp"],
        "irrelevant_sensors": ["dissolved_oxygen", "water_level", "soil_moisture", "mist_pressure"],
        "unique_fields": ["flood_frequency", "flood_duration", "grow_media_type", "tray_size", "reservoir_size", "reservoir_change_interval"],
        "ph_range": {"min": 5.5, "max": 6.5},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.4, "flower_min": 1.2, "flower_max": 1.8},
        "health_check_questions": ["Flood cycle timing (how often, how long)?", "Does the tray drain completely?", "Any overflow issues?", "Media staying moist between floods?"],
        "automations": ["flood_cycle_timer", "ph_auto_dose", "ec_auto_dose", "drain_confirmation", "overflow_alert", "stage_frequency_adjustment"],
        "feeding_approach": "Intermittent — nutrients delivered during flood cycles.",
        "nutrient_strength": "60-80%",
        "common_problems": ["Overflow", "Uneven drainage", "Salt buildup", "Timer failure", "Root rot"],
        "ai_prompt_context": "Ebb & Flow grow — tray floods periodically and drains back. Check flood/drain cycle timing, media moisture between floods, drainage completeness, and salt buildup.",
    },
    {
        "id": "drip",
        "name": "Drip / Top Feed",
        "category": "hydroponic_active",
        "description": "Nutrient solution dripped onto growing media from above via emitters.",
        "terminology": {"container": "Pot", "space": "Tent", "contents": "Media", "holder": "Pot", "medium": "Coco / Rockwool / Perlite", "drainage": "Runoff"},
        "sensor_kit": "Media Kit",
        "relevant_sensors": ["ph", "ec", "runoff_ph", "runoff_ec", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "runoff_ph", "runoff_ec"],
        "irrelevant_sensors": ["water_level", "dissolved_oxygen", "soil_moisture", "mist_pressure"],
        "unique_fields": ["drip_frequency", "drip_duration", "grow_media", "recirculating", "emitter_count", "reservoir_size", "target_runoff_pct"],
        "ph_range": {"min": 5.5, "max": 6.5},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.4, "flower_min": 1.2, "flower_max": 2.0},
        "health_check_questions": ["All emitters flowing?", "What's your runoff percentage?", "Input EC vs runoff EC?", "Media drying out between feeds?"],
        "automations": ["drip_timer", "ph_auto_dose", "ec_auto_dose", "runoff_ec_alert", "emitter_blockage_detection", "stage_frequency_adjustment"],
        "feeding_approach": "Scheduled drip events. More frequent in flower. Runoff management critical.",
        "nutrient_strength": "75-100%",
        "common_problems": ["Clogged emitters", "Uneven distribution", "Salt buildup", "Over/under watering"],
        "ai_prompt_context": "Drip/Top Feed grow — nutrient solution delivered via drip emitters onto media. Monitor emitter flow, runoff pH/EC delta, media moisture, and feed frequency.",
    },
    {
        "id": "aeroponics",
        "name": "Aeroponics",
        "category": "hydroponic_active",
        "description": "Roots suspended in air and misted with fine nutrient spray at high pressure.",
        "terminology": {"container": "Chamber", "space": "Tent", "contents": "Mist zone", "holder": "Net pot", "medium": "None (bare roots)"},
        "sensor_kit": "Aero Kit",
        "relevant_sensors": ["ph", "ec", "water_temp", "mist_pressure", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "mist_pressure"],
        "irrelevant_sensors": ["water_level", "soil_moisture", "soil_temp", "dissolved_oxygen"],
        "unique_fields": ["mist_on_seconds", "mist_off_seconds", "nozzle_pressure_psi", "nozzle_count", "reservoir_size", "reservoir_change_interval"],
        "ph_range": {"min": 5.5, "max": 6.2},
        "ec_range": {"seedling": 0.3, "veg_min": 0.6, "veg_max": 1.0, "flower_min": 1.0, "flower_max": 1.6},
        "health_check_questions": ["All nozzles misting?", "Mist cycle timing?", "Any roots drying out?", "System pressure reading?"],
        "automations": ["mist_cycle_timer", "ph_auto_dose", "ec_auto_dose", "pressure_monitor", "nozzle_failure_alert", "reservoir_temp_monitor"],
        "feeding_approach": "High-frequency mist cycles. Very low EC. Frequent reservoir changes.",
        "nutrient_strength": "40-60%",
        "common_problems": ["Nozzle clogs (lethal fast)", "Pressure loss", "Root drying", "Biofilm", "Pump failure"],
        "ai_prompt_context": "Aeroponic grow — roots misted with fine nutrient spray. Nozzle/pump failure is critical (roots dry in seconds). Monitor pressure, nozzle coverage, root health, and mist timing.",
    },
    {
        "id": "kratky",
        "name": "Kratky (Passive Hydro)",
        "category": "hydroponic_passive",
        "description": "No pumps or electricity. Roots grow into static nutrient solution as water level drops.",
        "terminology": {"container": "Container", "space": "Tent", "contents": "Nutrient solution", "holder": "Net pot", "medium": "Hydroton / Perlite"},
        "sensor_kit": "Kratky Kit",
        "relevant_sensors": ["ph", "ec", "water_temp", "water_level", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "water_level"],
        "irrelevant_sensors": ["dissolved_oxygen", "flow_rate", "mist_pressure", "soil_moisture"],
        "unique_fields": ["container_size", "initial_fill_level", "current_water_level", "target_air_gap", "refill_strategy"],
        "ph_range": {"min": 5.5, "max": 6.5},
        "ec_range": {"seedling": 0.5, "veg_min": 1.0, "veg_max": 1.6, "flower_min": 1.4, "flower_max": 2.0},
        "health_check_questions": ["Current water level?", "How much air gap above the water line?", "Any algae visible?", "Water color still clear/light?"],
        "automations": ["water_level_monitor", "ph_drift_alert", "ec_depletion_alert", "refill_reminder"],
        "feeding_approach": "Set-and-forget. Initial nutrient mix. Top-off only when critical. Never refill to top.",
        "nutrient_strength": "75-100%",
        "common_problems": ["Refilling too high", "Algae", "pH drift", "Nutrient depletion"],
        "ai_prompt_context": "Kratky passive hydro — NO pumps. Plants rely on air gap above water line for oxygen. NEVER refill to top level. Monitor water level drop, pH drift, and algae. Minimal intervention is the design.",
    },
    {
        "id": "coco",
        "name": "Coco Coir",
        "category": "soilless",
        "description": "Growing in coconut fiber. Functions like hydro with media buffer.",
        "terminology": {"container": "Pot", "space": "Tent", "contents": "Media", "holder": "Pot", "medium": "Coco coir", "drainage": "Runoff", "supplement": "CalMag"},
        "sensor_kit": "Media Kit",
        "relevant_sensors": ["ph", "ec", "runoff_ph", "runoff_ec", "soil_moisture", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "runoff_ec", "soil_moisture"],
        "irrelevant_sensors": ["water_level", "dissolved_oxygen", "water_temp", "mist_pressure"],
        "unique_fields": ["pot_size", "coco_type", "perlite_ratio", "watering_method", "watering_frequency", "target_runoff_pct", "calmag_supplement"],
        "ph_range": {"min": 5.8, "max": 6.2},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.4, "flower_min": 1.4, "flower_max": 2.2},
        "health_check_questions": ["Watering frequency?", "Input pH and EC?", "Runoff pH and EC?", "Using CalMag supplement?", "Coco pre-buffered?"],
        "automations": ["watering_schedule", "ph_auto_dose", "ec_auto_dose", "runoff_ec_alert", "dryback_monitor", "calmag_reminder", "stage_frequency_adjustment"],
        "feeding_approach": "Feed every watering (no plain water). Multiple times daily in flower. Target 10-20% runoff.",
        "nutrient_strength": "75-100%",
        "common_problems": ["CalMag deficiency", "Salt buildup", "Overwatering seedlings", "Drying out in flower"],
        "ai_prompt_context": "Coco coir grow — soilless media requiring nutrient solution every watering. CalMag supplementation critical. Monitor runoff EC vs input EC, never let coco dry fully, and increase watering frequency as plants grow.",
    },
    {
        "id": "rockwool",
        "name": "Rockwool",
        "category": "soilless",
        "description": "Growing in mineral wool cubes/slabs. Excellent water retention and air ratio.",
        "terminology": {"container": "Slab", "space": "Tent", "contents": "Slab", "holder": "Cube", "medium": "Rockwool", "drainage": "Runoff"},
        "sensor_kit": "Media Kit + Scale",
        "relevant_sensors": ["ph", "ec", "runoff_ph", "runoff_ec", "soil_moisture", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["ph", "ec", "soil_moisture"],
        "irrelevant_sensors": ["water_level", "dissolved_oxygen", "soil_temp", "mist_pressure"],
        "unique_fields": ["slab_size", "watering_method", "shots_per_day", "shot_volume_ml", "target_slab_moisture_pct", "slab_weight_tracking"],
        "ph_range": {"min": 5.5, "max": 6.0},
        "ec_range": {"seedling": 0.4, "veg_min": 0.8, "veg_max": 1.4, "flower_min": 1.4, "flower_max": 2.2},
        "health_check_questions": ["How many irrigation shots per day?", "Dry-back percentage overnight?", "Slab covered (algae prevention)?", "Pre-soaked rockwool before use?"],
        "automations": ["irrigation_shot_schedule", "dryback_monitor", "crop_steering", "ph_auto_dose", "ec_auto_dose", "runoff_ec_alert", "shot_volume_adjustment"],
        "feeding_approach": "Precision irrigation. Multiple small shots per day. Crop steering via dry-back percentage.",
        "nutrient_strength": "75-100%",
        "common_problems": ["pH too high if not pre-soaked", "Algae on surfaces", "Overwatering", "Poor dry-back strategy"],
        "ai_prompt_context": "Rockwool grow — precision irrigation in mineral wool slabs. Crop steering via dry-back percentage is key. Monitor slab moisture, shot timing/volume, runoff pH/EC, and cover exposed rockwool to prevent algae.",
    },
    {
        "id": "soil",
        "name": "Soil",
        "category": "traditional",
        "description": "Growing in organic or amended soil. Most forgiving medium.",
        "terminology": {"container": "Pot", "space": "Tent", "contents": "Soil", "holder": "Pot", "medium": "Soil / Super soil / Living soil"},
        "sensor_kit": "Soil Kit",
        "relevant_sensors": ["soil_moisture", "runoff_ph", "runoff_ec", "ambient_temp", "ambient_humidity"],
        "primary_sensors": ["soil_moisture", "ambient_temp", "ambient_humidity"],
        "irrelevant_sensors": ["water_temp", "dissolved_oxygen", "water_level", "ec", "flow_rate", "mist_pressure"],
        "unique_fields": ["pot_size", "soil_type", "organic_or_synthetic", "watering_method", "compost_tea_schedule", "top_dress_schedule", "beneficial_microbes"],
        "ph_range": {"min": 6.0, "max": 7.0},
        "ec_range": {"seedling": 0.3, "veg_min": 0.6, "veg_max": 1.0, "flower_min": 1.0, "flower_max": 1.6},
        "health_check_questions": ["Organic or synthetic nutrients?", "When did you last water?", "Pot weight (heavy or light)?", "Any bugs in the soil?", "Top dressed recently?", "Using mycorrhizae or beneficial microbes?"],
        "automations": ["watering_schedule", "soil_moisture_monitor", "watering_reminder", "top_dress_reminder", "compost_tea_reminder", "pest_check_reminder", "runoff_ph_alert"],
        "feeding_approach": "Wet/dry cycle. Water when top inch is dry. Feed every other watering (synthetic) or rely on amendments (organic).",
        "nutrient_strength": "50-75%",
        "common_problems": ["Overwatering", "Fungus gnats", "Nutrient lockout", "Root bound", "Slow deficiency detection"],
        "ai_prompt_context": "Soil grow — traditional media with natural buffering. Wet/dry cycle is important (do NOT keep constantly wet like hydro). Watch for overwatering, pest presence, and slower-developing deficiency signs.",
    },
    {
        "id": "outdoor_soil",
        "name": "Outdoor Soil",
        "category": "outdoor",
        "description": "Plants grown directly in ground soil or raised beds outdoors. Weather-dependent.",
        "terminology": {"container": "Plot", "space": "Garden", "contents": "Ground soil", "holder": "N/A", "medium": "Native soil / Amended soil"},
        "sensor_kit": "Outdoor Kit",
        "relevant_sensors": ["ambient_temp", "ambient_humidity", "soil_moisture", "soil_temp"],
        "primary_sensors": ["ambient_temp", "soil_moisture"],
        "irrelevant_sensors": ["ph", "ec", "water_temp", "dissolved_oxygen", "water_level", "flow_rate", "mist_pressure"],
        "unique_fields": ["plot_size", "soil_type", "soil_amendments", "sun_exposure", "companion_planting", "pest_deterrent", "irrigation_method", "frost_protection", "photoperiod_tracking"],
        "ph_range": {"min": 6.0, "max": 7.0},
        "ec_range": {"seedling": 0.0, "veg_min": 0.0, "veg_max": 0.0, "flower_min": 0.0, "flower_max": 0.0},
        "health_check_questions": ["Recent weather events (storms, frost, heatwave)?", "Any pest or animal damage visible?", "Soil moisture level?", "Hours of direct sunlight?", "Any support structures in place?"],
        "automations": ["weather_monitoring", "frost_warning", "watering_reminder", "photoperiod_tracking", "pest_check_reminder", "harvest_window_estimation", "rain_mold_alert", "smart_irrigation_skip"],
        "feeding_approach": "Amend soil before planting. Top dress or liquid feed monthly. Rain provides most water.",
        "nutrient_strength": "Minimal",
        "common_problems": ["Pests/animals", "Weather damage", "Light dep timing", "Mold in humid climates"],
        "ai_prompt_context": "Outdoor soil grow — weather-dependent, in-ground or raised bed. Factor in current weather when evaluating health. Watch for pest/animal damage, weather stress, photoperiod-triggered flowering, and mold risk.",
    },
    {
        "id": "outdoor_container",
        "name": "Outdoor Container",
        "category": "outdoor",
        "description": "Plants in containers outdoors. Combines container control with outdoor weather.",
        "terminology": {"container": "Pot", "space": "Patio", "contents": "Media", "holder": "Pot", "medium": "Soil / Coco-perlite"},
        "sensor_kit": "Outdoor Kit",
        "relevant_sensors": ["ambient_temp", "ambient_humidity", "soil_moisture", "runoff_ph", "runoff_ec"],
        "primary_sensors": ["ambient_temp", "soil_moisture"],
        "irrelevant_sensors": ["water_temp", "dissolved_oxygen", "water_level", "flow_rate", "mist_pressure"],
        "unique_fields": ["container_size", "media_type", "mobility", "saucer", "sun_exposure", "frost_protection", "irrigation_method"],
        "ph_range": {"min": 6.0, "max": 7.0},
        "ec_range": {"seedling": 0.3, "veg_min": 0.6, "veg_max": 1.0, "flower_min": 1.0, "flower_max": 1.6},
        "health_check_questions": ["Recent weather events?", "Any pest or animal damage?", "Container color (dark pots overheat)?", "Can you move plants indoors?", "Root bound signs?", "Container size adequate?"],
        "automations": ["weather_monitoring", "frost_warning", "watering_reminder", "container_temp_alert", "root_bound_reminder", "move_indoors_alert", "pest_check_reminder"],
        "feeding_approach": "Like soil/coco depending on media, but more frequent watering than in-ground.",
        "nutrient_strength": "Depends on media",
        "common_problems": ["Root bound", "Container overheating", "Faster drying", "Wind toppling", "Pests"],
        "ai_prompt_context": "Outdoor container grow — potted plants outside, weather-dependent. Container-specific concerns include root binding, pot overheating in direct sun, and faster drying than in-ground. Factor in weather data.",
    },
]
