"""ESPHome MQTT template generator — produces YAML configs for common sensor setups."""

from __future__ import annotations

TEMPLATES: dict[str, dict] = {
    "basic_ph_ec_temp": {
        "name": "Basic pH/EC/Temp",
        "description": "ESP32 with pH, EC, and DS18B20 water temperature sensors",
        "sensors": ["pH (analog)", "EC (analog)", "Water Temp (DS18B20)"],
        "board": "esp32dev",
    },
    "environment_monitor": {
        "name": "Environment Monitor",
        "description": "ESP32 with BME280 (temp/humidity/pressure) and light sensor",
        "sensors": ["Temperature (BME280)", "Humidity (BME280)", "Pressure (BME280)", "Light (BH1750)"],
        "board": "esp32dev",
    },
    "full_hydro_kit": {
        "name": "Full Hydro Kit",
        "description": "Complete hydroponic sensor suite: pH, EC, water temp, air temp/humidity, water level",
        "sensors": [
            "pH (analog)",
            "EC (analog)",
            "Water Temp (DS18B20)",
            "Air Temp/Humidity (SHT30)",
            "Water Level (ultrasonic)",
        ],
        "board": "esp32dev",
    },
    "soil_moisture": {
        "name": "Soil Moisture Array",
        "description": "ESP32 with 4 capacitive soil moisture sensors + DHT22",
        "sensors": ["Soil Moisture x4 (capacitive)", "Air Temp/Humidity (DHT22)"],
        "board": "esp32dev",
    },
    "co2_vpd_monitor": {
        "name": "CO2 & VPD Monitor",
        "description": "ESP32 with SCD40 CO2 sensor and SHT30 for VPD calculation",
        "sensors": ["CO2 (SCD40)", "Temperature (SHT30)", "Humidity (SHT30)"],
        "board": "esp32dev",
    },
}


def generate_yaml(
    template_id: str,
    device_name: str,
    mqtt_host: str,
    mqtt_user: str,
    mqtt_password: str,
    wifi_ssid: str,
    wifi_password: str,
) -> str:
    """Generate an ESPHome YAML config for a given template."""
    if template_id not in TEMPLATES:
        raise ValueError(f"Unknown template: {template_id}")

    tmpl = TEMPLATES[template_id]
    device_slug = device_name.lower().replace(" ", "-").replace("_", "-")

    yaml = f"""# ESPHome config generated by Tendril
# Template: {tmpl["name"]}
# Sensors: {", ".join(tmpl["sensors"])}

esphome:
  name: {device_slug}
  friendly_name: "{device_name}"

esp32:
  board: {tmpl["board"]}

wifi:
  ssid: "{wifi_ssid}"
  password: "{wifi_password}"
  ap:
    ssid: "{device_name} Fallback"
    password: "tendril-setup"

mqtt:
  broker: "{mqtt_host}"
  username: "{mqtt_user}"
  password: "{mqtt_password}"
  topic_prefix: "tendril/{device_slug}"
  discovery: false

logger:
  level: INFO

ota:
  platform: esphome
"""

    if template_id == "basic_ph_ec_temp":
        yaml += """
dallas:
  - pin: GPIO4

sensor:
  - platform: adc
    pin: GPIO34
    name: "pH"
    id: ph_sensor
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 14.0

  - platform: adc
    pin: GPIO35
    name: "EC"
    id: ec_sensor
    unit_of_measurement: "mS/cm"
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 5.0

  - platform: dallas
    address: 0x0000000000000000
    name: "Water Temperature"
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;
"""

    elif template_id == "environment_monitor":
        yaml += """
i2c:
  sda: GPIO21
  scl: GPIO22

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Temperature"
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * 9.0 / 5.0 + 32.0;
    humidity:
      name: "Humidity"
    pressure:
      name: "Pressure"
    update_interval: 30s

  - platform: bh1750
    name: "Light Intensity"
    unit_of_measurement: "lx"
    update_interval: 30s
"""

    elif template_id == "full_hydro_kit":
        yaml += """
dallas:
  - pin: GPIO4

i2c:
  sda: GPIO21
  scl: GPIO22

sensor:
  - platform: adc
    pin: GPIO34
    name: "pH"
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 14.0

  - platform: adc
    pin: GPIO35
    name: "EC"
    unit_of_measurement: "mS/cm"
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 3.3 -> 5.0

  - platform: dallas
    address: 0x0000000000000000
    name: "Water Temperature"
    unit_of_measurement: "°F"
    filters:
      - lambda: return x * 9.0 / 5.0 + 32.0;

  - platform: sht3xd
    temperature:
      name: "Air Temperature"
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * 9.0 / 5.0 + 32.0;
    humidity:
      name: "Air Humidity"
    update_interval: 30s

  - platform: ultrasonic
    trigger_pin: GPIO12
    echo_pin: GPIO14
    name: "Water Level"
    unit_of_measurement: "in"
    update_interval: 60s
    filters:
      - lambda: return x * 39.37;
"""

    elif template_id == "soil_moisture":
        yaml += """
sensor:
  - platform: adc
    pin: GPIO32
    name: "Soil Moisture 1"
    unit_of_measurement: "%"
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 3.3 -> 0.0
          - 1.0 -> 100.0

  - platform: adc
    pin: GPIO33
    name: "Soil Moisture 2"
    unit_of_measurement: "%"
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 3.3 -> 0.0
          - 1.0 -> 100.0

  - platform: adc
    pin: GPIO34
    name: "Soil Moisture 3"
    unit_of_measurement: "%"
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 3.3 -> 0.0
          - 1.0 -> 100.0

  - platform: adc
    pin: GPIO35
    name: "Soil Moisture 4"
    unit_of_measurement: "%"
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 3.3 -> 0.0
          - 1.0 -> 100.0

  - platform: dht
    pin: GPIO4
    model: DHT22
    temperature:
      name: "Air Temperature"
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * 9.0 / 5.0 + 32.0;
    humidity:
      name: "Air Humidity"
    update_interval: 30s
"""

    elif template_id == "co2_vpd_monitor":
        yaml += """
i2c:
  sda: GPIO21
  scl: GPIO22

sensor:
  - platform: scd4x
    co2:
      name: "CO2"
      unit_of_measurement: "ppm"
    update_interval: 30s

  - platform: sht3xd
    temperature:
      name: "Temperature"
      id: temp_sensor
      unit_of_measurement: "°F"
      filters:
        - lambda: return x * 9.0 / 5.0 + 32.0;
    humidity:
      name: "Humidity"
      id: humidity_sensor
    update_interval: 30s

  - platform: template
    name: "VPD"
    unit_of_measurement: "kPa"
    accuracy_decimals: 2
    lambda: |-
      float t = id(temp_sensor).state;
      float rh = id(humidity_sensor).state;
      float tc = (t - 32.0) * 5.0 / 9.0;
      float svp = 0.6108 * exp(17.27 * tc / (tc + 237.3));
      float vpd = svp * (1.0 - rh / 100.0);
      return vpd;
    update_interval: 30s
"""

    return yaml


def list_templates() -> list[dict]:
    """Return all available templates with metadata."""
    return [{"id": tid, **{k: v for k, v in t.items() if k != "board"}} for tid, t in TEMPLATES.items()]
