"""Strain database sync — imports reference strains from curated seed data.

The curated ``SEED_STRAINS`` list is the source of truth for the global strain
library. THC/CBD are stored as a typical (midpoint) value plus the commonly
observed min/max range, because real-world potency varies by phenotype,
cultivation, and testing lab. See ``STRAIN_DATA_CAVEAT``.
"""

from __future__ import annotations

import logging
from datetime import UTC, date, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.grows.models import ReferenceStrain

logger = logging.getLogger("tendril.reference.strains")

# Date the curated dataset below was last cross-referenced against public databases.
LAST_VERIFIED = date(2026, 7, 20)

# Honest provenance/accuracy note surfaced in the API and AI prompts. Cannabis
# potency is inherently variable — a single "correct" number does not exist.
STRAIN_DATA_CAVEAT = (
    "Cannabinoid, terpene, flowering-time and yield figures are typical ranges aggregated from "
    "public strain databases (Leafly, Wikileaf, AllBud, SeedFinder) and breeder listings. Actual "
    "results vary by phenotype, cultivation method, and testing lab."
)

# Standard aggregator sources the consensus values are drawn from.
_SRC = ["Leafly", "Wikileaf", "AllBud", "SeedFinder"]

# Curated seed data for common strains (avoids dependency on external API availability)
SEED_STRAINS: list[dict] = [
    {
        "name": "Blue Dream",
        "breeder": "DJ Short / Santa Cruz",
        "genetics": "Blueberry x Haze",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 40,
        "sativa_pct": 60,
        "thc_pct": 18.0,
        "thc_min": 17.0,
        "thc_max": 24.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 2.0,
        "terpenes": ["myrcene", "pinene", "caryophyllene"],
        "effects": ["euphoric", "creative", "uplifted", "relaxed", "happy"],
        "flavors": ["blueberry", "berry", "sweet", "herbal"],
        "flowering_min_weeks": 9.0,
        "flowering_max_weeks": 10.0,
        "yield_indoor": "~600 g/m²",
        "yield_outdoor": "~600 g/plant",
        "description": "Sativa-dominant hybrid. Sweet berry aroma, balanced cerebral and body effects.",
        "sources": _SRC,
    },
    {
        "name": "Girl Scout Cookies",
        "breeder": "Cookie Family",
        "genetics": "OG Kush x Durban Poison",
        "strain_type": "Indica-dominant hybrid",
        "indica_pct": 60,
        "sativa_pct": 40,
        "thc_pct": 25.0,
        "thc_min": 19.0,
        "thc_max": 28.0,
        "cbd_pct": 0.2,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "limonene", "humulene"],
        "effects": ["euphoric", "relaxed", "happy", "uplifted", "creative"],
        "flavors": ["sweet", "earthy", "mint", "cookie", "pungent"],
        "flowering_min_weeks": 9.0,
        "flowering_max_weeks": 10.0,
        "yield_indoor": "~300-400 g/m²",
        "yield_outdoor": "~400 g/plant",
        "description": "Hybrid. Sweet, earthy, pungent. Strong euphoria with full-body relaxation.",
        "sources": _SRC,
    },
    {
        "name": "OG Kush",
        "breeder": "Unknown (FL origin)",
        "genetics": "Chemdawg x Hindu Kush x Lemon Thai",
        "strain_type": "Hybrid (indica-leaning)",
        "indica_pct": 55,
        "sativa_pct": 45,
        "thc_pct": 23.0,
        "thc_min": 19.0,
        "thc_max": 26.0,
        "cbd_pct": 0.3,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["myrcene", "limonene", "caryophyllene"],
        "effects": ["relaxed", "happy", "euphoric", "hungry", "sleepy"],
        "flavors": ["earthy", "pine", "woody", "diesel", "lemon"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~500 g/plant",
        "description": "Indica-dominant hybrid. Fuel, skunk, spice. Heavy euphoria, stress relief.",
        "sources": _SRC,
    },
    {
        "name": "Gorilla Glue #4",
        "breeder": "GG Strains",
        "genetics": "Chem's Sister x Sour Dubb x Chocolate Diesel",
        "strain_type": "Hybrid (balanced)",
        "indica_pct": 50,
        "sativa_pct": 50,
        "thc_pct": 28.0,
        "thc_min": 25.0,
        "thc_max": 30.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "limonene", "myrcene"],
        "effects": ["relaxed", "euphoric", "happy", "uplifted", "sleepy"],
        "flavors": ["earthy", "diesel", "pine", "pungent", "chocolate"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~500-600 g/m²",
        "yield_outdoor": "~600 g/plant",
        "description": "Hybrid. Pine, chocolate, diesel. Extremely potent, couch-lock.",
        "sources": _SRC,
    },
    {
        "name": "Gelato",
        "breeder": "Cookie Family",
        "genetics": "Sunset Sherbet x Thin Mint GSC",
        "strain_type": "Hybrid (indica-leaning)",
        "indica_pct": 55,
        "sativa_pct": 45,
        "thc_pct": 24.0,
        "thc_min": 20.0,
        "thc_max": 26.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "limonene", "humulene"],
        "effects": ["relaxed", "euphoric", "happy", "creative", "uplifted"],
        "flavors": ["sweet", "citrus", "berry", "creamy", "lavender"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~500 g/m²",
        "yield_outdoor": "~450 g/plant",
        "description": "Hybrid. Sweet, citrus, lavender. Balanced relaxation with mental stimulation.",
        "sources": _SRC,
    },
    {
        "name": "Wedding Cake",
        "breeder": "Seed Junky Genetics",
        "genetics": "Triangle Kush x Animal Mints",
        "strain_type": "Indica-dominant hybrid",
        "indica_pct": 60,
        "sativa_pct": 40,
        "thc_pct": 25.0,
        "thc_min": 22.0,
        "thc_max": 27.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["limonene", "caryophyllene", "myrcene"],
        "effects": ["relaxed", "happy", "euphoric", "uplifted", "hungry"],
        "flavors": ["sweet", "vanilla", "earthy", "pepper", "tangy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450-500 g/m²",
        "yield_outdoor": "~500 g/plant",
        "description": "Indica-dominant. Sweet, tangy, earthy. Relaxing, euphoric.",
        "sources": _SRC,
    },
    {
        "name": "Jack Herer",
        "breeder": "Sensi Seeds",
        "genetics": "Haze x Northern Lights #5 x Shiva Skunk",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 45,
        "sativa_pct": 55,
        "thc_pct": 20.0,
        "thc_min": 18.0,
        "thc_max": 24.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["terpinolene", "caryophyllene", "pinene"],
        "effects": ["happy", "uplifted", "energetic", "creative", "focused"],
        "flavors": ["earthy", "pine", "woody", "citrus", "spicy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 10.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~550 g/plant",
        "description": "Sativa-dominant. Pine, spice, floral. Creative, blissful, clear-headed.",
        "sources": [*_SRC, "Sensi Seeds"],
    },
    {
        "name": "Northern Lights",
        "breeder": "Sensi Seeds",
        "genetics": "Afghani x Thai (landrace)",
        "strain_type": "Indica (near-pure)",
        "indica_pct": 90,
        "sativa_pct": 10,
        "thc_pct": 18.0,
        "thc_min": 16.0,
        "thc_max": 21.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["myrcene", "caryophyllene", "pinene"],
        "effects": ["relaxed", "sleepy", "happy", "euphoric", "hungry"],
        "flavors": ["earthy", "sweet", "pine", "spicy"],
        "flowering_min_weeks": 7.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450-550 g/m²",
        "yield_outdoor": "~600 g/plant",
        "description": "Near-pure indica. Sweet, spicy, earthy. Heavy body stone, pain relief. Easy to grow.",
        "sources": [*_SRC, "Sensi Seeds"],
    },
    {
        "name": "Sour Diesel",
        "breeder": "Unknown (East Coast)",
        "genetics": "Chemdawg 91 x Super Skunk",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 30,
        "sativa_pct": 70,
        "thc_pct": 22.0,
        "thc_min": 18.0,
        "thc_max": 25.0,
        "cbd_pct": 0.2,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "limonene", "myrcene"],
        "effects": ["energetic", "happy", "uplifted", "euphoric", "creative"],
        "flavors": ["diesel", "pungent", "citrus", "earthy"],
        "flowering_min_weeks": 10.0,
        "flowering_max_weeks": 11.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~550 g/plant",
        "description": "Sativa-dominant. Diesel, citrus. Energizing, dreamy cerebral effects.",
        "sources": _SRC,
    },
    {
        "name": "White Widow",
        "breeder": "Green House Seeds",
        "genetics": "Brazilian Sativa x South Indian Indica",
        "strain_type": "Hybrid (balanced)",
        "indica_pct": 50,
        "sativa_pct": 50,
        "thc_pct": 20.0,
        "thc_min": 18.0,
        "thc_max": 25.0,
        "cbd_pct": 0.2,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["myrcene", "pinene", "caryophyllene"],
        "effects": ["euphoric", "energetic", "happy", "uplifted", "creative"],
        "flavors": ["earthy", "woody", "pungent", "spicy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~500 g/m²",
        "yield_outdoor": "~600 g/plant",
        "description": "Balanced hybrid. Earthy, woody, pungent. Powerful euphoria with creativity.",
        "sources": [*_SRC, "Green House Seeds"],
    },
    {
        "name": "AK-47",
        "breeder": "Serious Seeds",
        "genetics": "Colombian x Mexican x Thai x Afghani",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 35,
        "sativa_pct": 65,
        "thc_pct": 20.0,
        "thc_min": 16.0,
        "thc_max": 22.0,
        "cbd_pct": 0.3,
        "cbd_min": 0.0,
        "cbd_max": 1.5,
        "terpenes": ["myrcene", "caryophyllene", "pinene"],
        "effects": ["relaxed", "happy", "uplifted", "euphoric", "creative"],
        "flavors": ["earthy", "floral", "sweet", "sour", "woody"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~550 g/plant",
        "description": "Sativa-dominant. Earthy, floral, sweet. Long-lasting cerebral buzz.",
        "sources": [*_SRC, "Serious Seeds"],
    },
    {
        "name": "Purple Punch",
        "breeder": "Supernova Gardens",
        "genetics": "Larry OG x Granddaddy Purple",
        "strain_type": "Indica-dominant hybrid",
        "indica_pct": 80,
        "sativa_pct": 20,
        "thc_pct": 20.0,
        "thc_min": 18.0,
        "thc_max": 25.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "limonene", "pinene"],
        "effects": ["relaxed", "sleepy", "happy", "euphoric", "hungry"],
        "flavors": ["grape", "berry", "sweet", "vanilla", "candy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~400-500 g/m²",
        "yield_outdoor": "~500 g/plant",
        "description": "Indica-dominant. Grape, blueberry, vanilla. Sedating, pain relief.",
        "sources": _SRC,
    },
    {
        "name": "Zkittlez",
        "breeder": "3rd Gen Family / Terp Hogz",
        "genetics": "Grape Ape x Grapefruit",
        "strain_type": "Indica-dominant hybrid",
        "indica_pct": 70,
        "sativa_pct": 30,
        "thc_pct": 19.0,
        "thc_min": 15.0,
        "thc_max": 23.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "humulene", "linalool"],
        "effects": ["relaxed", "happy", "euphoric", "uplifted", "calm"],
        "flavors": ["sweet", "tropical", "berry", "grape", "candy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~400 g/m²",
        "yield_outdoor": "~500 g/plant",
        "description": "Indica-dominant. Sweet, tropical, berry. Calming, happy, focused.",
        "sources": _SRC,
    },
    {
        "name": "Runtz",
        "breeder": "Cookies",
        "genetics": "Zkittlez x Gelato",
        "strain_type": "Hybrid (balanced)",
        "indica_pct": 50,
        "sativa_pct": 50,
        "thc_pct": 24.0,
        "thc_min": 19.0,
        "thc_max": 29.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["caryophyllene", "limonene", "linalool"],
        "effects": ["euphoric", "relaxed", "happy", "uplifted", "giggly"],
        "flavors": ["sweet", "fruity", "candy", "berry", "creamy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~400-450 g/m²",
        "yield_outdoor": "~450 g/plant",
        "description": "Hybrid. Sweet candy, fruity, creamy. Euphoric, giggly, relaxing.",
        "sources": _SRC,
    },
    {
        "name": "Mimosa",
        "breeder": "Symbiotic Genetics",
        "genetics": "Clementine x Purple Punch",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 30,
        "sativa_pct": 70,
        "thc_pct": 22.0,
        "thc_min": 19.0,
        "thc_max": 27.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["limonene", "caryophyllene", "myrcene"],
        "effects": ["energetic", "uplifted", "happy", "focused", "euphoric"],
        "flavors": ["citrus", "orange", "sweet", "tropical", "earthy"],
        "flowering_min_weeks": 9.0,
        "flowering_max_weeks": 10.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~550 g/plant",
        "description": "Sativa-dominant. Citrus, tropical, sweet. Uplifting, energetic, focused.",
        "sources": _SRC,
    },
    {
        "name": "Do-Si-Dos",
        "breeder": "Archive Seed Bank",
        "genetics": "Girl Scout Cookies x Face Off OG",
        "strain_type": "Indica-dominant hybrid",
        "indica_pct": 70,
        "sativa_pct": 30,
        "thc_pct": 26.0,
        "thc_min": 19.0,
        "thc_max": 30.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["limonene", "caryophyllene", "linalool"],
        "effects": ["relaxed", "sleepy", "happy", "euphoric", "hungry"],
        "flavors": ["sweet", "earthy", "floral", "pine", "pungent"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~500 g/plant",
        "description": "Indica-dominant. Earthy, sweet, floral. Powerful body relaxation.",
        "sources": _SRC,
    },
    {
        "name": "Granddaddy Purple",
        "breeder": "Ken Estes",
        "genetics": "Purple Urkle x Big Bud",
        "strain_type": "Indica-dominant",
        "indica_pct": 80,
        "sativa_pct": 20,
        "thc_pct": 20.0,
        "thc_min": 17.0,
        "thc_max": 23.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["myrcene", "caryophyllene", "pinene"],
        "effects": ["relaxed", "sleepy", "happy", "euphoric", "hungry"],
        "flavors": ["grape", "berry", "sweet", "earthy"],
        "flowering_min_weeks": 8.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450-500 g/m²",
        "yield_outdoor": "~600 g/plant",
        "description": "Indica-dominant. Grape, berry, sweet. Full-body relaxation, sleepy.",
        "sources": _SRC,
    },
    {
        "name": "Green Crack",
        "breeder": "Cecil C.",
        "genetics": "Skunk #1 x Isolated Afghani Cut",
        "strain_type": "Sativa-dominant",
        "indica_pct": 35,
        "sativa_pct": 65,
        "thc_pct": 21.0,
        "thc_min": 15.0,
        "thc_max": 25.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["myrcene", "caryophyllene", "limonene"],
        "effects": ["energetic", "focused", "happy", "uplifted", "euphoric"],
        "flavors": ["citrus", "mango", "sweet", "tropical", "earthy"],
        "flowering_min_weeks": 7.0,
        "flowering_max_weeks": 9.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~550 g/plant",
        "description": "Sativa-dominant. Mango, citrus, sweet. Sharp energy, mental focus.",
        "sources": _SRC,
    },
    {
        "name": "Bruce Banner",
        "breeder": "Dark Horse Genetics",
        "genetics": "OG Kush x Strawberry Diesel",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 40,
        "sativa_pct": 60,
        "thc_pct": 27.0,
        "thc_min": 24.0,
        "thc_max": 29.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["myrcene", "caryophyllene", "limonene"],
        "effects": ["euphoric", "energetic", "happy", "creative", "relaxed"],
        "flavors": ["diesel", "sweet", "earthy", "berry", "pungent"],
        "flowering_min_weeks": 9.0,
        "flowering_max_weeks": 10.0,
        "yield_indoor": "~500 g/m²",
        "yield_outdoor": "~600 g/plant",
        "description": "Hybrid. Diesel, sweet, earthy. Extremely potent, euphoric, creative.",
        "sources": _SRC,
    },
    {
        "name": "MAC (Miracle Alien Cookies)",
        "breeder": "Capulator",
        "genetics": "Alien Cookies x Colombian x Starfighter",
        "strain_type": "Hybrid (balanced)",
        "indica_pct": 50,
        "sativa_pct": 50,
        "thc_pct": 23.0,
        "thc_min": 20.0,
        "thc_max": 26.0,
        "cbd_pct": 0.1,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["limonene", "caryophyllene", "pinene"],
        "effects": ["happy", "uplifted", "euphoric", "relaxed", "creative"],
        "flavors": ["citrus", "floral", "creamy", "diesel", "spicy"],
        "flowering_min_weeks": 9.0,
        "flowering_max_weeks": 10.0,
        "yield_indoor": "~400 g/m²",
        "yield_outdoor": "~450 g/plant",
        "description": "Hybrid. Citrus, floral, dough. Creative, happy, uplifting.",
        "sources": _SRC,
    },
    {
        "name": "Citrus Mistress",
        "breeder": "Unknown",
        "genetics": "Haze x Skunk #1 x Northern Lights #5",
        "strain_type": "Sativa-dominant hybrid",
        "indica_pct": 10,
        "sativa_pct": 90,
        "thc_pct": 23.0,
        "thc_min": 20.0,
        "thc_max": 26.0,
        "cbd_pct": 0.2,
        "cbd_min": 0.0,
        "cbd_max": 1.0,
        "terpenes": ["terpinolene", "limonene", "caryophyllene"],
        "effects": ["energetic", "euphoric", "creative", "uplifted", "hungry"],
        "flavors": ["citrus", "sour", "spicy", "earthy", "haze"],
        "flowering_min_weeks": 10.0,
        "flowering_max_weeks": 11.0,
        "yield_indoor": "~450 g/m²",
        "yield_outdoor": "~550 g/plant",
        "description": (
            "Sativa-dominant hybrid (~90% sativa). Sour citrus, spicy haze, earthy undertone. "
            "Energizing wake-and-bake — euphoric, creative, uplifting, appetite-stimulating. "
            "Long-flowering Haze lineage."
        ),
        "sources": ["AllBud"],
    },
]


async def sync_seed_strains(session: AsyncSession) -> int:
    """Seed the reference_strains table with curated data. Returns count of new strains added."""
    added = 0
    for strain_data in SEED_STRAINS:
        existing = (
            await session.execute(select(ReferenceStrain).where(ReferenceStrain.name == strain_data["name"]))
        ).scalar_one_or_none()

        if existing:
            # Update existing record
            for key, value in strain_data.items():
                setattr(existing, key, value)
            existing.last_verified = LAST_VERIFIED
            existing.synced_at = datetime.now(UTC)
        else:
            strain = ReferenceStrain(
                **strain_data,
                external_id=f"seed:{strain_data['name'].lower().replace(' ', '-')}",
                last_verified=LAST_VERIFIED,
                synced_at=datetime.now(UTC),
            )
            session.add(strain)
            added += 1

    await session.commit()
    logger.info("Strain sync complete: %d new, %d total", added, len(SEED_STRAINS))
    return added
