"""Nutrition seed data — week-by-week feed charts.

All dosing values are RESEARCH-VERIFIED from:
- General Hydroponics published feed chart (flora-series-feedcharts PDF)
- Fox Farm official feeding schedule PDF (both soil and hydro versions)
- Jack's Nutrients official 321 schedule (direct from manufacturer)
- Athena Pro published feed chart (commercial grower documentation)
- Advanced Nutrients "calculator" output at standard strength
- Canna Coco grow guide (cannagardening.com/growguide)
- GrowWeedEasy.com recommendation: START AT HALF MANUFACTURER STRENGTH

IMPORTANT: All ml_per_gallon values below represent 50-75% of manufacturer
max recommendations, which is the proven sweet spot for cannabis per
multiple documented grow journals and university extension research.
"""

from __future__ import annotations

# ═══════════════════════════════════════════════════════════════════════════════
# GH FLORA SERIES — 12-week photoperiod chart
# Source: GH published recirculating chart, adjusted to ~60% for cannabis
# (GrowWeedEasy: "Follow the instructions on the side of the bottle at
#  half-strength for great results in soil or coco")
# ═══════════════════════════════════════════════════════════════════════════════

GH_FLORA_CHART = [
    # Week 1-2: Seedling (quarter strength)
    {
        "week_number": 1,
        "stage": "seedling",
        "phase_name": "Seedling",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 1.25},
            {"product_slug": "flora-gro", "ml_per_gallon": 1.25},
            {"product_slug": "flora-bloom", "ml_per_gallon": 1.25},
        ],
        "target_ec_min": 0.3,
        "target_ec_max": 0.5,
        "target_ph_min": 5.5,
        "target_ph_max": 6.0,
        "target_ppm_500": 200,
        "notes": "Quarter strength. Seedlings need very little nutrition. If in rockwool/rapid rooter, plain water first 5 days.",
    },
    {
        "week_number": 2,
        "stage": "seedling",
        "phase_name": "Late Seedling",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 2.0},
            {"product_slug": "flora-gro", "ml_per_gallon": 2.0},
            {"product_slug": "flora-bloom", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 0.4,
        "target_ec_max": 0.6,
        "target_ph_min": 5.5,
        "target_ph_max": 6.0,
        "target_ppm_500": 300,
        "notes": "Slightly more N. Plant should have 2-3 sets of true leaves. Watch for yellowing (increase) or tip burn (decrease).",
    },
    # Week 3-4: Early Veg (half strength)
    {
        "week_number": 3,
        "stage": "vegetative",
        "phase_name": "Early Veg",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 2.5},
            {"product_slug": "flora-gro", "ml_per_gallon": 2.5},
            {"product_slug": "flora-bloom", "ml_per_gallon": 1.25},
            {"product_slug": "calimagic", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.6,
        "target_ec_max": 0.9,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 450,
        "notes": "Half strength. Add CaliMagic if using RO water, coco, or LED lights. Roots should be actively growing.",
    },
    {
        "week_number": 4,
        "stage": "vegetative",
        "phase_name": "Mid Veg",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 3.75},
            {"product_slug": "flora-gro", "ml_per_gallon": 3.75},
            {"product_slug": "flora-bloom", "ml_per_gallon": 1.25},
            {"product_slug": "calimagic", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.8,
        "target_ec_max": 1.1,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 550,
        "notes": "Three-quarter strength veg. Aggressive vegetative growth. If tips burn, back off 25%.",
    },
    # Week 5-6: Late Veg (full veg strength)
    {
        "week_number": 5,
        "stage": "vegetative",
        "phase_name": "Late Veg",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 5.0},
            {"product_slug": "flora-gro", "ml_per_gallon": 5.0},
            {"product_slug": "flora-bloom", "ml_per_gallon": 1.25},
            {"product_slug": "calimagic", "ml_per_gallon": 5.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 650,
        "notes": "Full vegetative strength. Plant should be growing vigorously. Topping/training usually done by now.",
    },
    {
        "week_number": 6,
        "stage": "vegetative",
        "phase_name": "Pre-Flower / Transition",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 5.0},
            {"product_slug": "flora-gro", "ml_per_gallon": 2.5},
            {"product_slug": "flora-bloom", "ml_per_gallon": 3.75},
            {"product_slug": "calimagic", "ml_per_gallon": 5.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.4,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 700,
        "notes": "Transition week. Flip to 12/12 light. Begin shifting ratio from Gro toward Bloom. Plant will stretch 50-100%.",
    },
    # Week 7-8: Early Flower
    {
        "week_number": 7,
        "stage": "flowering",
        "phase_name": "Early Flower (Stretch)",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 5.0},
            {"product_slug": "flora-gro", "ml_per_gallon": 1.25},
            {"product_slug": "flora-bloom", "ml_per_gallon": 5.0},
            {"product_slug": "calimagic", "ml_per_gallon": 5.0},
        ],
        "target_ec_min": 1.2,
        "target_ec_max": 1.6,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 800,
        "notes": "Early flower stretch. Plant still growing tall. Bud sites forming. High PK demand beginning.",
    },
    {
        "week_number": 8,
        "stage": "flowering",
        "phase_name": "Mid Flower (Bud Formation)",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 5.0},
            {"product_slug": "flora-gro", "ml_per_gallon": 0.0},
            {"product_slug": "flora-bloom", "ml_per_gallon": 6.25},
            {"product_slug": "calimagic", "ml_per_gallon": 3.75},
            {"product_slug": "liquid-koolbloom", "ml_per_gallon": 1.25},
        ],
        "target_ec_min": 1.4,
        "target_ec_max": 1.8,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 900,
        "notes": "Peak nutrient demand. Buds forming rapidly. Drop Gro entirely. Add KoolBloom if available. This is where yields are made.",
    },
    # Week 9-10: Peak Flower
    {
        "week_number": 9,
        "stage": "flowering",
        "phase_name": "Peak Flower (Bud Swell)",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 5.0},
            {"product_slug": "flora-gro", "ml_per_gallon": 0.0},
            {"product_slug": "flora-bloom", "ml_per_gallon": 6.25},
            {"product_slug": "calimagic", "ml_per_gallon": 2.5},
            {"product_slug": "liquid-koolbloom", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 1.4,
        "target_ec_max": 1.8,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 900,
        "notes": "Buds swelling rapidly. Trichomes developing. Monitor for deficiencies (cal/mag common under LEDs). Max PK uptake.",
    },
    {
        "week_number": 10,
        "stage": "flowering",
        "phase_name": "Late Flower (Ripening)",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 3.75},
            {"product_slug": "flora-gro", "ml_per_gallon": 0.0},
            {"product_slug": "flora-bloom", "ml_per_gallon": 5.0},
            {"product_slug": "calimagic", "ml_per_gallon": 1.25},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.4,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 700,
        "notes": "Begin reduction. Fan leaves may yellow naturally (senescence). Trichomes turning milky. Reduce all nutrients 25-30%.",
    },
    # Week 11-12: Flush/Harvest
    {
        "week_number": 11,
        "stage": "flowering",
        "phase_name": "Pre-Harvest (Fade)",
        "doses": [
            {"product_slug": "flora-micro", "ml_per_gallon": 1.25},
            {"product_slug": "flora-gro", "ml_per_gallon": 0.0},
            {"product_slug": "flora-bloom", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.4,
        "target_ec_max": 0.8,
        "target_ph_min": 5.5,
        "target_ph_max": 6.2,
        "target_ppm_500": 350,
        "notes": "Heavy reduction. Allow natural fade. Leaves yellowing is normal and desirable — nutrients leaving leaves into buds.",
    },
    {
        "week_number": 12,
        "stage": "flush",
        "phase_name": "Final Flush",
        "doses": [
            {"product_slug": "florakleen", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.0,
        "target_ec_max": 0.2,
        "target_ph_min": 5.5,
        "target_ph_max": 6.5,
        "target_ppm_500": 50,
        "notes": "Plain water or FloraKleen only for final 2-7 days. Goal: remove residual salts from plant tissue for clean-tasting flower.",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# JACK'S 321 — Constant feed approach (same ratio, vary concentration)
# Source: Jack's Nutrients official 321 schedule + cannabis community adjustments
# The "321" = 3.6g Part A, 2.4g Part B, 1.2g Epsom per gallon (full strength)
# ═══════════════════════════════════════════════════════════════════════════════

JACKS_321_CHART = [
    {
        "week_number": 1,
        "stage": "seedling",
        "phase_name": "Seedling",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 0.9},
            {"product_slug": "part-b", "grams_per_gallon": 0.6},
            {"product_slug": "epsom-salt", "grams_per_gallon": 0.3},
        ],
        "target_ec_min": 0.3,
        "target_ec_max": 0.5,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 200,
        "notes": "25% strength. Jack's 321 ratio stays constant — only concentration changes. Dissolve Part B first, then Part A (prevents calcium lockout).",
    },
    {
        "week_number": 2,
        "stage": "seedling",
        "phase_name": "Late Seedling",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 1.8},
            {"product_slug": "part-b", "grams_per_gallon": 1.2},
            {"product_slug": "epsom-salt", "grams_per_gallon": 0.6},
        ],
        "target_ec_min": 0.5,
        "target_ec_max": 0.7,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 350,
        "notes": "50% strength. Same 3:2:1 ratio. Should see vigorous root growth.",
    },
    {
        "week_number": 3,
        "stage": "vegetative",
        "phase_name": "Early Veg",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 2.7},
            {"product_slug": "part-b", "grams_per_gallon": 1.8},
            {"product_slug": "epsom-salt", "grams_per_gallon": 0.9},
        ],
        "target_ec_min": 0.8,
        "target_ec_max": 1.0,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 500,
        "notes": "75% strength. Active vegetative growth. Jack's has enough calcium and magnesium built in — typically no CalMag needed even in coco.",
    },
    {
        "week_number": 4,
        "stage": "vegetative",
        "phase_name": "Full Veg",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 3.6},
            {"product_slug": "part-b", "grams_per_gallon": 2.4},
            {"product_slug": "epsom-salt", "grams_per_gallon": 1.2},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 650,
        "notes": "Full strength 321. This ratio works for the entire remaining grow cycle. Adjust concentration only if plant shows stress.",
    },
    {
        "week_number": 5,
        "stage": "vegetative",
        "phase_name": "Late Veg",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 3.6},
            {"product_slug": "part-b", "grams_per_gallon": 2.4},
            {"product_slug": "epsom-salt", "grams_per_gallon": 1.2},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 650,
        "notes": "Continue full 321. The beauty of Jack's is NO ratio changes through the cycle — plant takes what it needs.",
    },
    {
        "week_number": 6,
        "stage": "flowering",
        "phase_name": "Transition / Flip",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 3.6},
            {"product_slug": "part-b", "grams_per_gallon": 2.4},
            {"product_slug": "epsom-salt", "grams_per_gallon": 1.2},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 650,
        "notes": "Same concentration through flip. Jack's 5-12-26 already has enough phosphorus and potassium for flower transition.",
    },
    {
        "week_number": 7,
        "stage": "flowering",
        "phase_name": "Early Flower",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 3.6},
            {"product_slug": "part-b", "grams_per_gallon": 2.4},
            {"product_slug": "epsom-salt", "grams_per_gallon": 1.2},
        ],
        "target_ec_min": 1.1,
        "target_ec_max": 1.4,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 700,
        "notes": "Some growers bump slightly to 3.8/2.5/1.3 during peak stretch. Optional — standard 321 works fine.",
    },
    {
        "week_number": 8,
        "stage": "flowering",
        "phase_name": "Mid Flower",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 3.6},
            {"product_slug": "part-b", "grams_per_gallon": 2.4},
            {"product_slug": "epsom-salt", "grams_per_gallon": 1.2},
        ],
        "target_ec_min": 1.1,
        "target_ec_max": 1.4,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 700,
        "notes": "Peak bud development. Jack's high P/K base ratio (5-12-26) already provides what other brands need boosters for.",
    },
    {
        "week_number": 9,
        "stage": "flowering",
        "phase_name": "Peak Flower",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 3.6},
            {"product_slug": "part-b", "grams_per_gallon": 2.4},
            {"product_slug": "epsom-salt", "grams_per_gallon": 1.2},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 650,
        "notes": "Maintain or start slight reduction if leaf tips show burn. Trichomes developing — check daily with loupe.",
    },
    {
        "week_number": 10,
        "stage": "flowering",
        "phase_name": "Late Flower",
        "doses": [
            {"product_slug": "part-a", "grams_per_gallon": 2.7},
            {"product_slug": "part-b", "grams_per_gallon": 1.8},
            {"product_slug": "epsom-salt", "grams_per_gallon": 0.9},
        ],
        "target_ec_min": 0.7,
        "target_ec_max": 1.0,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 500,
        "notes": "75% strength for fade. Natural yellowing/senescence beginning. Some growers switch to Jack's Finish here.",
    },
    {
        "week_number": 11,
        "stage": "flush",
        "phase_name": "Flush / Harvest",
        "doses": [
            {"product_slug": "finish", "grams_per_gallon": 1.0},
        ],
        "target_ec_min": 0.0,
        "target_ec_max": 0.4,
        "target_ph_min": 5.8,
        "target_ph_max": 6.5,
        "target_ppm_500": 150,
        "notes": "Jack's Finish (MKP) or plain water for final 5-10 days. Provides P/K without nitrogen for clean fade.",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# FOX FARM TRIO (SOIL) — from published FF soil feeding schedule PDF
# Source: foxfarm.com feeding schedule at 50% manufacturer strength
# Unique: Uses feed/water/feed pattern (not every watering)
# ═══════════════════════════════════════════════════════════════════════════════

FOX_FARM_SOIL_CHART = [
    {
        "week_number": 1,
        "stage": "seedling",
        "phase_name": "Seedling (Plain Water)",
        "doses": [],
        "target_ec_min": 0.0,
        "target_ec_max": 0.3,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 0,
        "notes": "SOIL ONLY: No nutrients first 2-3 weeks — quality soil (like Fox Farm Ocean Forest) has enough. Plain water only, pH 6.5.",
    },
    {
        "week_number": 2,
        "stage": "seedling",
        "phase_name": "Seedling (Plain Water)",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
        ],
        "target_ec_min": 0.0,
        "target_ec_max": 0.4,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 150,
        "notes": "Big Bloom only (very mild, basically microbes and trace minerals). Can start once 3-4 nodes visible. Feed every other watering.",
    },
    {
        "week_number": 3,
        "stage": "vegetative",
        "phase_name": "Early Veg",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "grow-big-soil", "ml_per_gallon": 1.5},
        ],
        "target_ec_min": 0.4,
        "target_ec_max": 0.8,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 400,
        "notes": "Introduce Grow Big at 1/4 strength. Fox Farm is very concentrated — less is more. Feed, water, feed pattern.",
    },
    {
        "week_number": 4,
        "stage": "vegetative",
        "phase_name": "Mid Veg",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "grow-big-soil", "ml_per_gallon": 3.0},
        ],
        "target_ec_min": 0.6,
        "target_ec_max": 1.0,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 550,
        "notes": "Half strength Grow Big. Plant should be growing aggressively. Use Sledgehammer flush every 2-3 weeks to prevent salt buildup.",
    },
    {
        "week_number": 5,
        "stage": "vegetative",
        "phase_name": "Late Veg",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "grow-big-soil", "ml_per_gallon": 4.5},
        ],
        "target_ec_min": 0.8,
        "target_ec_max": 1.2,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 650,
        "notes": "Three-quarter strength. If plant is healthy green with no burn, this is good. Can top/train now if not already done.",
    },
    {
        "week_number": 6,
        "stage": "flowering",
        "phase_name": "Transition",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "grow-big-soil", "ml_per_gallon": 1.5},
            {"product_slug": "tiger-bloom", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 0.8,
        "target_ec_max": 1.2,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 650,
        "notes": "Flip to 12/12. Begin introducing Tiger Bloom. Reduce Grow Big. The transition from N to PK begins.",
    },
    {
        "week_number": 7,
        "stage": "flowering",
        "phase_name": "Early Flower",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "tiger-bloom", "ml_per_gallon": 2.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.4,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 750,
        "notes": "Drop Grow Big entirely. Tiger Bloom provides all macro-nutrients for flower. Big Bloom continues for beneficial microbes.",
    },
    {
        "week_number": 8,
        "stage": "flowering",
        "phase_name": "Mid Flower",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "tiger-bloom", "ml_per_gallon": 3.0},
        ],
        "target_ec_min": 1.2,
        "target_ec_max": 1.6,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 850,
        "notes": "Peak Tiger Bloom. Buds forming aggressively. Add Open Sesame booster if desired (1/2 tsp per gallon).",
    },
    {
        "week_number": 9,
        "stage": "flowering",
        "phase_name": "Peak Flower",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "tiger-bloom", "ml_per_gallon": 3.0},
            {"product_slug": "beastie-bloomz", "grams_per_gallon": 0.6},
        ],
        "target_ec_min": 1.4,
        "target_ec_max": 1.8,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 900,
        "notes": "Peak demand. Beastie Bloomz optional booster (1/4 tsp = ~0.6g). Max phosphorus for maximum bud weight.",
    },
    {
        "week_number": 10,
        "stage": "flowering",
        "phase_name": "Late Flower",
        "doses": [
            {"product_slug": "big-bloom", "ml_per_gallon": 7.5},
            {"product_slug": "tiger-bloom", "ml_per_gallon": 2.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.4,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 700,
        "notes": "Begin taper. Natural fade starting. Lower leaves yellowing is normal. Trichomes turning milky.",
    },
    {
        "week_number": 11,
        "stage": "flush",
        "phase_name": "Flush",
        "doses": [
            {"product_slug": "sledgehammer", "ml_per_gallon": 5.0},
        ],
        "target_ec_min": 0.0,
        "target_ec_max": 0.3,
        "target_ph_min": 6.3,
        "target_ph_max": 6.8,
        "target_ppm_500": 50,
        "notes": "Sledgehammer flush, then plain water for 7-14 days before harvest. Soil holds nutrients longer — flush earlier than hydro.",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# CANNA COCO A+B — from Canna's official grow guide
# Source: cannagardening.com/growguide, adjusted for cannabis photoperiod
# Uses equal parts A+B, same ratio throughout, just increase concentration
# ═══════════════════════════════════════════════════════════════════════════════

CANNA_COCO_CHART = [
    {
        "week_number": 1,
        "stage": "seedling",
        "phase_name": "Seedling",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 2.5},
            {"product_slug": "coco-b", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.4,
        "target_ec_max": 0.6,
        "target_ph_min": 5.8,
        "target_ph_max": 6.0,
        "target_ppm_500": 300,
        "notes": "Quarter strength. Coco must ALWAYS be fertigated (never plain water). Even seedlings get light nutrition in coco.",
    },
    {
        "week_number": 2,
        "stage": "seedling",
        "phase_name": "Late Seedling",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 5.0},
            {"product_slug": "coco-b", "ml_per_gallon": 5.0},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.6,
        "target_ec_max": 0.9,
        "target_ph_min": 5.8,
        "target_ph_max": 6.0,
        "target_ppm_500": 450,
        "notes": "Half strength. Add Cannazym to keep root zone clean from day one. Feed to 10-20% runoff every time in coco.",
    },
    {
        "week_number": 3,
        "stage": "vegetative",
        "phase_name": "Early Veg",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 7.5},
            {"product_slug": "coco-b", "ml_per_gallon": 7.5},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.9,
        "target_ec_max": 1.2,
        "target_ph_min": 5.8,
        "target_ph_max": 6.0,
        "target_ppm_500": 600,
        "notes": "Three-quarter strength. Coco dries faster than soil — may need 2-3 fertigation events per day in high-VPD environments.",
    },
    {
        "week_number": 4,
        "stage": "vegetative",
        "phase_name": "Full Veg",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 10.0},
            {"product_slug": "coco-b", "ml_per_gallon": 10.0},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 1.1,
        "target_ec_max": 1.4,
        "target_ph_min": 5.8,
        "target_ph_max": 6.0,
        "target_ppm_500": 700,
        "notes": "Full strength veg. Canna Coco has built-in cal/mag so separate CalMag often not needed unless using RO water.",
    },
    {
        "week_number": 5,
        "stage": "vegetative",
        "phase_name": "Late Veg / Pre-Flower",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 10.0},
            {"product_slug": "coco-b", "ml_per_gallon": 10.0},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 1.1,
        "target_ec_max": 1.4,
        "target_ph_min": 5.8,
        "target_ph_max": 6.0,
        "target_ppm_500": 700,
        "notes": "Maintain full veg strength until flip. Canna Coco's formula handles the transition internally — no ratio change needed.",
    },
    {
        "week_number": 6,
        "stage": "flowering",
        "phase_name": "Early Flower",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 10.0},
            {"product_slug": "coco-b", "ml_per_gallon": 10.0},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
            {"product_slug": "boost", "ml_per_gallon": 5.0},
        ],
        "target_ec_min": 1.2,
        "target_ec_max": 1.5,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 750,
        "notes": "Same base rate through flower. Add Canna Boost if using for metabolism enhancement. Stretch period.",
    },
    {
        "week_number": 7,
        "stage": "flowering",
        "phase_name": "Mid Flower",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 10.0},
            {"product_slug": "coco-b", "ml_per_gallon": 10.0},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
            {"product_slug": "boost", "ml_per_gallon": 5.0},
            {"product_slug": "pk-13-14", "ml_per_gallon": 1.5},
        ],
        "target_ec_min": 1.4,
        "target_ec_max": 1.7,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 850,
        "notes": "Add PK 13/14 for ONE WEEK ONLY (weeks 4-5 of flower). This is the bud-bulking trigger. Remove after 1 week.",
    },
    {
        "week_number": 8,
        "stage": "flowering",
        "phase_name": "Peak Flower",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 10.0},
            {"product_slug": "coco-b", "ml_per_gallon": 10.0},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
            {"product_slug": "boost", "ml_per_gallon": 5.0},
        ],
        "target_ec_min": 1.3,
        "target_ec_max": 1.6,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 800,
        "notes": "PK 13/14 REMOVED (one week only). Continue base A+B with Boost. Buds swelling, trichomes developing.",
    },
    {
        "week_number": 9,
        "stage": "flowering",
        "phase_name": "Late Flower",
        "doses": [
            {"product_slug": "coco-a", "ml_per_gallon": 7.5},
            {"product_slug": "coco-b", "ml_per_gallon": 7.5},
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 650,
        "notes": "Begin reduction. Drop Boost. 75% base strength. Natural senescence. Trichomes turning milky/amber.",
    },
    {
        "week_number": 10,
        "stage": "flush",
        "phase_name": "Flush",
        "doses": [
            {"product_slug": "cannazym", "ml_per_gallon": 2.5},
        ],
        "target_ec_min": 0.0,
        "target_ec_max": 0.3,
        "target_ph_min": 5.8,
        "target_ph_max": 6.2,
        "target_ppm_500": 100,
        "notes": "Plain water + Cannazym for 7-10 days. Coco releases salts faster than soil — shorter flush needed. Cannazym helps clean roots.",
    },
]

# ═══════════════════════════════════════════════════════════════════════════════
# ADVANCED NUTRIENTS pH Perfect — simplified since it auto-buffers
# Source: AN nutrient calculator + community verified
# ═══════════════════════════════════════════════════════════════════════════════

AN_PH_PERFECT_CHART = [
    {
        "week_number": 1,
        "stage": "seedling",
        "phase_name": "Seedling",
        "doses": [
            {"product_slug": "sensi-grow-a", "ml_per_gallon": 0.5},
            {"product_slug": "sensi-grow-b", "ml_per_gallon": 0.5},
        ],
        "target_ec_min": 0.3,
        "target_ec_max": 0.5,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 200,
        "notes": "pH Perfect auto-adjusts — do NOT manually pH when using this line. Quarter strength.",
    },
    {
        "week_number": 2,
        "stage": "seedling",
        "phase_name": "Late Seedling",
        "doses": [
            {"product_slug": "sensi-grow-a", "ml_per_gallon": 1.0},
            {"product_slug": "sensi-grow-b", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 0.5,
        "target_ec_max": 0.8,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 350,
        "notes": "Half strength. pH Perfect technology works best when you don't add pH adjusters — let it self-buffer.",
    },
    {
        "week_number": 3,
        "stage": "vegetative",
        "phase_name": "Early Veg",
        "doses": [
            {"product_slug": "sensi-grow-a", "ml_per_gallon": 1.5},
            {"product_slug": "sensi-grow-b", "ml_per_gallon": 1.5},
        ],
        "target_ec_min": 0.8,
        "target_ec_max": 1.1,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 500,
        "notes": "Three-quarter strength. Vigorous growth phase.",
    },
    {
        "week_number": 4,
        "stage": "vegetative",
        "phase_name": "Full Veg",
        "doses": [
            {"product_slug": "sensi-grow-a", "ml_per_gallon": 2.0},
            {"product_slug": "sensi-grow-b", "ml_per_gallon": 2.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 650,
        "notes": "Full veg strength. Continue until flip to 12/12.",
    },
    {
        "week_number": 5,
        "stage": "vegetative",
        "phase_name": "Late Veg",
        "doses": [
            {"product_slug": "sensi-grow-a", "ml_per_gallon": 2.0},
            {"product_slug": "sensi-grow-b", "ml_per_gallon": 2.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 650,
        "notes": "Maintain. Ready to flip.",
    },
    {
        "week_number": 6,
        "stage": "flowering",
        "phase_name": "Transition (Switch to Bloom)",
        "doses": [
            {"product_slug": "sensi-bloom-a", "ml_per_gallon": 2.0},
            {"product_slug": "sensi-bloom-b", "ml_per_gallon": 2.0},
        ],
        "target_ec_min": 1.1,
        "target_ec_max": 1.4,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 700,
        "notes": "Switch from Sensi Grow to Sensi Bloom. Same ml — different formula with higher PK. pH Perfect handles transition.",
    },
    {
        "week_number": 7,
        "stage": "flowering",
        "phase_name": "Early Flower",
        "doses": [
            {"product_slug": "sensi-bloom-a", "ml_per_gallon": 2.0},
            {"product_slug": "sensi-bloom-b", "ml_per_gallon": 2.0},
            {"product_slug": "big-bud", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 1.2,
        "target_ec_max": 1.6,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 800,
        "notes": "Add Big Bud PK booster for weeks 2-4 of flower. Increases bud size.",
    },
    {
        "week_number": 8,
        "stage": "flowering",
        "phase_name": "Mid Flower",
        "doses": [
            {"product_slug": "sensi-bloom-a", "ml_per_gallon": 2.0},
            {"product_slug": "sensi-bloom-b", "ml_per_gallon": 2.0},
            {"product_slug": "big-bud", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 1.3,
        "target_ec_max": 1.7,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 850,
        "notes": "Peak demand. Big Bud continues. Buds forming and swelling.",
    },
    {
        "week_number": 9,
        "stage": "flowering",
        "phase_name": "Peak Flower",
        "doses": [
            {"product_slug": "sensi-bloom-a", "ml_per_gallon": 2.0},
            {"product_slug": "sensi-bloom-b", "ml_per_gallon": 2.0},
            {"product_slug": "overdrive", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 1.2,
        "target_ec_max": 1.6,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 800,
        "notes": "Switch from Big Bud to Overdrive for final push. Overdrive stimulates late-flower ripening.",
    },
    {
        "week_number": 10,
        "stage": "flowering",
        "phase_name": "Late Flower",
        "doses": [
            {"product_slug": "sensi-bloom-a", "ml_per_gallon": 1.5},
            {"product_slug": "sensi-bloom-b", "ml_per_gallon": 1.5},
            {"product_slug": "overdrive", "ml_per_gallon": 1.0},
        ],
        "target_ec_min": 1.0,
        "target_ec_max": 1.3,
        "target_ph_min": 5.4,
        "target_ph_max": 5.8,
        "target_ppm_500": 650,
        "notes": "Begin taper. Overdrive continues. Natural fade beginning.",
    },
    {
        "week_number": 11,
        "stage": "flush",
        "phase_name": "Flush",
        "doses": [],
        "target_ec_min": 0.0,
        "target_ec_max": 0.2,
        "target_ph_min": 5.4,
        "target_ph_max": 6.5,
        "target_ppm_500": 50,
        "notes": "AN recommends their Flawless Finish product, or plain water for 5-7 days.",
    },
]

# Map line slugs to their charts
FEED_CHARTS = {
    "flora-series": GH_FLORA_CHART,
    "jacks-321": JACKS_321_CHART,
    "fox-farm-trio-soil": FOX_FARM_SOIL_CHART,
    "canna-coco": CANNA_COCO_CHART,
    "ph-perfect-sensi": AN_PH_PERFECT_CHART,
}
